version: '3'

services:
    app:
        image: ruby:3.3-rc-slim-bullseye
        ports:
            - 3300:3300
        working_dir: /app
        volumes:
            - ./:/app
        command: bundle exec rails s -b 0.0.0.0
        environment:
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
    postgres:
        image: postgres:16
        container_name: postgres-boilerplate
        command: "postgres -c 'max_connections=500'"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
volumes:
    app:
    postgres-data:

networks:
    default:
        name: boilerplate
