version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - database
        volumes:
            - ./:/app
            - gem_cache:/usr/local/bundle/gems
        env_file: .env
        environment:
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
    database:
        image: postgres:16
        container_name: postgres-boilerplate
        command: "postgres -c 'max_connections=500'"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
volumes:
    postgres-data:
    gem_cache:

networks:
    default:
        name: boilerplate
