version: '3.8'
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - database
        volumes:
            - ./:/usr/src/app
        env_file: .env
        environment:
            DB_HOST: database
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
    database:
        image: postgres:16
        container_name: local-postgres
        command: "postgres -c 'max_connections=500'"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
volumes:
    postgres-data: {}
