development:
  adapter: async
  url: ws://localhost:3000/cable

test:
  adapter: async
  url: ws://localhost:3000/cable

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://10.10.10.10:6379/1" } %>
  channel_prefix: app_production
